export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_CATEGORY_PRODUCT = 'GET_CATEGORY_PRODUCT'
export const CATEGORY_LOADING = 'CATEGORY_LOADING'

export const GET_CART = 'GET_CART'
export const ADD_CART = 'ADD_CART'
export const DELETE_CART = 'DELETE_CART'
export const CART_LOADING = 'CART_LOADING'

export const GET_PRODUCT = 'GET_PRODUCT'
export const PRODUCT_LOADING = 'PRODUCT_LOADING'

export const GET_ORDER = 'GET_ORDER'
export const ORDER_LOADING = 'ORDER_LOADING'